### ISSUE TITLE
information on unrecognized css rules

### ISSUE THREAD

**Issue by JLarky** [miklosme/css-to-tailwind#5]
I wish there was a way to get information that rule was not converted or wasn't executed precisely. The main idea that if I have CSS and I convert it to a tailwind and convert it back to CSS I will not lose any information :)

Example of losing data for unrecognized options:
```css
.getsIgnored {
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  -webkit-tap-highlight-color: transparent;
}
```

Second example:
```css
@keyframes mymove {
  from {top: 0px;}
  to {top: 200px;}
}
```

Example of loosing data with not precise variants:
```css
.button {
  padding: 1.6rem;
}

@media (min-width: 777px) {
  .button {
    padding: 0.5rem;
  } 
}

@media (min-width: 999px) {
  .button {
    padding: 3rem;
  } 
}
```

I'm using https://transform.tools/css-to-tailwind to test the package

I propose some kind of `raw` option that returns raw css in case if it wasn't recognized like
```js
{selector: "@keyframes mymove", missing: {}, tailwind: "", raw: "@keyframes mymove {from {top: 0px;} to {top: 200px;}}"}
```
